create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  level text not null default 'Core',
  summary text not null default '',
  lesson_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.courses
  add column if not exists level text not null default 'Core',
  add column if not exists summary text not null default '',
  add column if not exists lesson_count integer not null default 0,
  add column if not exists created_at timestamptz not null default now();

insert into public.courses (id, title, level, summary, lesson_count)
values
  (1, 'Forex Foundations', 'Core', 'Market structure, currency pairs, sessions, pips, order flow, and broker execution fundamentals.', 4),
  (2, 'Forex Anatomy', 'Core', 'Understand the Forex market as a living system by studying its structure, liquidity, institutional activity, economic forces, trading sessions, and broker execution environment.', 8),
  (3, 'Technical Analysis Lab', 'Applied', 'Candlestick reading, support and resistance, trend systems, multi-timeframe confirmation, and chart review.', 4),
  (4, 'Risk and Capital Protection', 'Professional', 'Position sizing, drawdown control, trade invalidation, loss limits, and portfolio-level risk rules.', 4),
  (5, 'Institutional Forex Strategy', 'Advanced', 'Liquidity concepts, macro catalysts, news discipline, and professional trade planning routines.', 4)
on conflict (id) do update
set title = excluded.title,
    level = excluded.level,
    summary = excluded.summary,
    lesson_count = excluded.lesson_count;

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  slug text not null,
  title text not null,
  lesson_order integer not null,
  created_at timestamptz not null default now(),
  unique (course_id, slug)
);

insert into public.lessons (id, course_id, slug, title, lesson_order)
values
  (1, 1, 'fx-market-map', 'The Forex Market Map', 1),
  (2, 1, 'currency-pairs', 'Currency Pairs and Quote Anatomy', 2),
  (3, 1, 'sessions-pips', 'Sessions, Pips, Lots and Spreads', 3),
  (4, 1, 'orders-execution', 'Orders, Execution and Broker Basics', 4),
  (5, 2, 'market-structure-skeleton', 'The Skeleton: Market Structure', 1),
  (6, 2, 'institutional-orders-muscles', 'The Muscles: Institutional Orders', 2),
  (7, 2, 'order-flow-blood', 'The Blood Flow: Order Flow', 3),
  (8, 2, 'economic-data-nervous-system', 'The Nervous System: Economic Data', 4),
  (9, 2, 'liquidity-heart', 'The Heart: Liquidity', 5),
  (10, 2, 'trading-sessions-clock', 'The Clock: Trading Sessions', 6),
  (11, 2, 'broker-interface-skin', 'The Skin: Broker Interface', 7),
  (12, 2, 'central-banks-brain', 'The Brain: Central Banks', 8),
  (13, 3, 'candlestick-structure', 'Candlestick Structure and Context', 1),
  (14, 3, 'support-resistance', 'Support, Resistance, and Liquidity Zones', 2),
  (15, 3, 'trend-confirmation', 'Trend Systems and Confirmation', 3),
  (16, 3, 'multi-timeframe', 'Multi-Timeframe Analysis Lab', 4),
  (17, 4, 'position-sizing', 'Position Sizing Frameworks', 1),
  (18, 4, 'drawdown-control', 'Drawdown Control and Daily Loss Rules', 2),
  (19, 4, 'trade-invalidation', 'Trade Invalidation and Stop Logic', 3),
  (20, 4, 'risk-review', 'Risk Review and Capital Protection Plan', 4),
  (21, 5, 'liquidity-concepts', 'Institutional Liquidity Concepts', 1),
  (22, 5, 'macro-catalysts', 'Macro Catalysts and Currency Bias', 2),
  (23, 5, 'news-discipline', 'News Discipline and Volatility Controls', 3),
  (24, 5, 'trade-planning', 'Professional Trade Planning Routine', 4)
on conflict (course_id, slug) do update
set title = excluded.title,
    lesson_order = excluded.lesson_order;

grant select on public.courses to authenticated;
grant select on public.lessons to authenticated;

alter table public.courses enable row level security;
alter table public.lessons enable row level security;

drop policy if exists "Authenticated users can read courses" on public.courses;
drop policy if exists "Authenticated users can read lessons" on public.lessons;

create policy "Authenticated users can read courses"
on public.courses
for select
to authenticated
using (true);

create policy "Authenticated users can read lessons"
on public.lessons
for select
to authenticated
using (true);

notify pgrst, 'reload schema';
