-- Student registration support for public.students.
-- Run this in Supabase SQL Editor if the live students table is missing these fields.

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text,
  country text,
  enrollment_date date not null default current_date,
  certification_level text not null default 'Forex Training Division',
  status text not null default 'Active',
  created_at timestamptz not null default now()
);

alter table public.students
  add column if not exists full_name text,
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists country text,
  add column if not exists enrollment_date date not null default current_date,
  add column if not exists certification_level text not null default 'Forex Training Division',
  add column if not exists status text not null default 'Active',
  add column if not exists created_at timestamptz not null default now();

alter table public.students enable row level security;

grant insert on public.students to anon;
grant select, insert on public.students to authenticated;

drop policy if exists "Public can create student registrations" on public.students;
drop policy if exists "Authenticated users can create student registrations" on public.students;

create policy "Public can create student registrations"
on public.students
for insert
to anon
with check (true);

create policy "Authenticated users can create student registrations"
on public.students
for insert
to authenticated
with check (true);

notify pgrst, 'reload schema';
